CREATE TABLE schedule (
  Day DATE NOT NULL, 
  Faculty VARCHAR(50) NOT NULL,
  Fellow VARCHAR(50) NOT NULL,
  RN1 VARCHAR(50) NOT NULL,
  RN2 VARCHAR(50) NOT NULL,
  Tech1 VARCHAR(50) NOT NULL,
  Tech2 VARCHAR(50) NOT NULL,
  PRIMARY KEY(Day)
)