CREATE TABLE tblDayViewCalendar (
  PRIMARY KEY HourID VARCHAR(50) NOT NULL AUTO_INCREMENT
  DayID VARCHAR(50) NOT NULL, 
  ShiftHour TIMESTAMP NOT NULL, 
  Faculty VARCHAR(50),
  Fellow VARCHAR(50),
  RN1 VARCHAR(50),
  RN2 VARCHAR(50),
  Tech1 VARCHAR(50),
  Tech2 VARCHAR(50)
);