CREATE TABLE tblMonthViewCalendar (
  PRIMARY KEY DayID VARCHAR(50) NOT NULL AUTO_INCREMENT
  Day DATE NOT NULL, 
  Faculty VARCHAR(50),
  Fellow VARCHAR(50),
  RN1 VARCHAR(50),
  RN2 VARCHAR(50),
  Tech1 VARCHAR(50),
  Tech2 VARCHAR(50)
);