CREATE TABLE tblUser (
  PRIMARY KEY UserID VARCHAR(50) NOT NULL AUTO_INCREMENT,
  Role VARCHAR(50) NOT NULL,
  IsAdministrator BOOLEAN,
  FirstName VARCHAR(50) NOT NULL,
  LastName VARCHAR(50) NOT NULL,
  CellPhone INTEGER(12) NOT NULL,
  HomePhone INTEGER(12) NOT NULL,
  PagerNumber INTEGER(12) NOT NULL,
  NetID VARCHAR(50)
);